project_id = "vfswqkrxwrjzimpzvhen"

[functions.chat]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.check-payment]
verify_jwt = true

[functions.get-price]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.extract-memories]
verify_jwt = true

[functions.save-memory]
verify_jwt = false
