project_id = "vfswqkrxwrjzimpzvhen"

[functions.chat]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.check-payment]
verify_jwt = true

[functions.get-price]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.extract-memories]
verify_jwt = false

[functions.save-memory]
verify_jwt = false

[functions.get-payment-links]
verify_jwt = false

[functions.verify-stripe-session]
verify_jwt = false

[functions.claim-purchase]
verify_jwt = true

[functions.create-user]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-signup-reminder]
verify_jwt = false

[functions.list-stripe-prices]
verify_jwt = false

[functions.submit-quiz]
verify_jwt = false
