// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-chapters.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_chapters_default = defineTool({
  name: "list_chapters",
  title: "List course chapters",
  description: "List the WiseFamilies course chapters (published) with their id, title, description, and order.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("chapters").select("id, title, description, order_number, status").eq("status", "published").order("order_number", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { chapters: data }
    };
  }
});

// src/lib/mcp/tools/list-modules.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_modules_default = defineTool2({
  name: "list_modules",
  title: "List course modules",
  description: "List published course modules, optionally filtered to a single chapter. Returns id, title, description, chapter_id, and order.",
  inputSchema: {
    chapter_id: z.string().uuid().optional().describe("Optional chapter id to filter by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ chapter_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser2(ctx).from("modules").select("id, title, description, chapter_id, order_number, status").eq("status", "published").order("order_number", { ascending: true });
    if (chapter_id) query = query.eq("chapter_id", chapter_id);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { modules: data }
    };
  }
});

// src/lib/mcp/tools/get-my-progress.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_progress_default = defineTool3({
  name: "get_my_progress",
  title: "Get my course progress",
  description: "Return the signed-in parent's progress across all course modules: which they've started, which they've completed, and totals.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const [{ data: progress, error: pErr }, { data: modules, error: mErr }] = await Promise.all([
      sb.from("user_progress").select("module_id, started_at, completed_at").eq("user_id", ctx.getUserId()),
      sb.from("modules").select("id, title, chapter_id, order_number").eq("status", "published")
    ]);
    if (pErr || mErr) {
      return {
        content: [{ type: "text", text: (pErr ?? mErr).message }],
        isError: true
      };
    }
    const completed = (progress ?? []).filter((p) => p.completed_at).length;
    const started = (progress ?? []).filter((p) => p.started_at && !p.completed_at).length;
    const summary = {
      total_modules: modules?.length ?? 0,
      completed,
      in_progress: started,
      progress,
      modules
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-my-documents.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_documents_default = defineTool4({
  name: "list_my_documents",
  title: "List my documents",
  description: "List generated documents belonging to the signed-in parent (Family Agreements, 30-Day Plans, etc.).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("user_documents").select("id, title, document_type, module_id, created_at, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { documents: data }
    };
  }
});

// src/lib/mcp/tools/get-document.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_document_default = defineTool5({
  name: "get_document",
  title: "Get a document",
  description: "Fetch the full contents (JSON body) of one of the signed-in parent's generated documents by id.",
  inputSchema: {
    document_id: z2.string().uuid().describe("The document id from list_my_documents.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ document_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("user_documents").select("id, title, document_type, module_id, document_data, created_at, updated_at").eq("user_id", ctx.getUserId()).eq("id", document_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Document not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { document: data }
    };
  }
});

// src/lib/mcp/tools/list-my-memories.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_memories_default = defineTool6({
  name: "list_my_memories",
  title: "List remembered family facts",
  description: "List the key facts WiseFamilies has remembered about the signed-in parent's family (child age, interests, challenges, etc.).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser6(ctx).from("user_memories").select("memory_key, memory_value, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { memories: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vfswqkrxwrjzimpzvhen";
var mcp_default = defineMcp({
  name: "wisefamilies-mcp",
  title: "WiseFamilies",
  version: "0.1.0",
  instructions: "Tools for the WiseFamilies AI-Ready Family course. Use these to look up the parent's course chapters and modules, read their progress, and fetch their generated Family Agreements and 30-Day Plans. All tools act as the signed-in parent.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_chapters_default,
    list_modules_default,
    get_my_progress_default,
    list_my_documents_default,
    get_document_default,
    list_my_memories_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
